name: challege_2026
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: null
  dartz: null
  firebase_auth: null
  firebase_core: null
  firebase_messaging: null
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_lints: null
  flutter_map: ^8.2.2
  flutter_screenutil: null
  freezed_annotation: null
  get: null
  get_storage: null
  json_serializable: null
  latlong2: ^0.9.1
  rxdart: null
  xml: ^6.6.1

dev_dependencies:
  build_runner: null

  # #to make native splash screen
  # # 1) change path image_path
  # # 2) run commened -> flutter pub run flutter_native_splash:create
  #   flutter_native_splash: ^2.1.1
  # flutter_native_splash:
  #   background_image: assets/image/splash_background.png # choose one color or background
  #   color: "#ffffff"
  #   image: assets/icons/icon.png
  # # to change icon
  # # 1) change path image_path
  # # 2) run commened -> flutter pub run flutter_launcher_icons:main
  #   flutter_launcher_icons: ^0.9.2
  # flutter_icons:
  #   android: true
  #   ios: true
  #   remove_alpha_ios: true
  #   image_path: "assets/icons/icon.png"
  flutter_test:
    sdk: flutter
  freezed: null

flutter:
  assets:
    - .env
    - assets/icons/
    - assets/image/
    - assets/animation/
    - assets/gpx/
  uses-material-design: true
